<?php

namespace AppBundle\Repository;

/**
 * periodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class periodsRepository extends \Doctrine\ORM\EntityRepository
{
}
